/*
 * This source file was generated by the Gradle 'init' task
 */
package registroapp1;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Clase principal que demuestra el uso de Log4j
 */
public class App {
    private static final Logger logger = LogManager.getLogger(App.class);
    
    public static void main(String[] args) {
        logger.info("=== INICIANDO APLICACIÓN DE REGISTRO ===");
        
        RegistroApp app = new RegistroApp();
        
        try {
            // Ejecutar diferentes demostraciones
            app.demostrarPatronesLogging();
            
            System.out.println("\n" + "=".repeat(50));
            
            app.ejecutarOperaciones();
            
            System.out.println("\n" + "=".repeat(50));
            
            app.simularErrores();
            
        } catch (Exception e) {
            logger.fatal("Error crítico en la aplicación", e);
        }
        
        logger.info("=== APLICACIÓN FINALIZADA ===");
        
        // Información adicional para el usuario
        System.out.println("\n" + "=".repeat(50));
        System.out.println("INFORMACIÓN SOBRE LOS LOGS:");
        System.out.println("- Los logs se muestran en la consola");
        System.out.println("- Los logs también se guardan en: logs/registro-app.log");
        System.out.println("- Los logs con rotación se guardan en: logs/registro-app-rolling.log");
        System.out.println("- Revisa los archivos de log para ver el historial completo");
        System.out.println("=".repeat(50));
    }
}
